vich_uploader:
    db_driver: orm

    mappings:
        wiki_cover:
            uri_prefix: /images/wiki
            upload_destination: '%kernel.project_dir%/public/images/wiki'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
